version: '3.8'

services:
  app1:
    build: .
    container_name: fiber_app1
    restart: always
    environment:
      - PORT=3000
      - REDIS_HOST=redis:6379
    depends_on:
      - redis

  app2:
    build: .
    container_name: fiber_app2
    restart: always
    environment:
      - PORT=3000
      - REDIS_HOST=redis:6379
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: nginx_load_balancer
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
