version: '3.8'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fiber_app1
    restart: always
    env_file:
      - .env
    depends_on:
      - redis

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fiber_app2
    restart: always
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env

  nginx:
    profiles:
      - prod
    image: nginx:latest
    container_name: nginx_load_balancer
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
